name: doc_appointment
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  intl_utils: ^2.1.0
  cupertino_icons: ^1.0.2
  firebase_core: ^2.23.0
  firebase_auth: ^4.14.1
  firebase_messaging: ^14.7.10
  google_sign_in: ^6.1.6
  cloud_firestore: ^4.13.1
  firebase_storage: ^11.5.2
  shared_preferences: ^2.2.2
  flutter_riverpod: ^2.4.8
  go_router: ^12.1.1
  google_fonts: ^6.1.0
  image_picker: ^1.0.4 # This was already included, ensure it's updated if needed
  uuid: ^4.3.3
  path: ^1.8.3
  table_calendar: ^3.0.2
  date_time_picker: ^2.0.0
  file_picker: ^4.5.0 # Added for picking files
  path_provider: ^2.0.9 # Added for accessing the file system path
  permission_handler: ^10.4.5 # Added for handling permissions

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/

dependency_overrides:
  intl: ^0.18.1
