final List<Map<String, dynamic>> doctorsList = [
  {
    'name': 'Dr. Olivia',
    'specialty': 'Gastroenterology',
    'availability': 'Morning',
    'schedule': 'Weekdays',
    'area': 'Jahra',
  },
  {
    'name': 'Dr. Farid',
    'specialty': 'Ophthalmology',
    'availability': 'Evening',
    'schedule': 'Weekends',
    'area': 'Assima',
  },
  {
    'name': 'Dr. Lily',
    'specialty': 'Dermatology',
    'availability': 'Afternoon',
    'schedule': 'Weekdays',
    'area': 'Hawally',
  },
  {
    'name': 'Dr. Ahmed',
    'specialty': 'Cardiology',
    'availability': 'Morning',
    'schedule': 'Weekends',
    'area': 'Jahra',
  },
  {
    'name': 'Dr. Nora',
    'specialty': 'Orthopedics',
    'availability': 'Evening',
    'schedule': 'Weekdays',
    'area': 'Assima',
  },
  {
    'name': 'Dr. Mohammad',
    'specialty': 'Gastroenterology',
    'availability': 'Afternoon',
    'schedule': 'Weekends',
    'area': 'Hawally',
  },
  {
    'name': 'Dr. Aisha',
    'specialty': 'Ophthalmology',
    'availability': 'Morning',
    'schedule': 'Weekdays',
    'area': 'Jahra',
  },
  {
    'name': 'Dr. Samir',
    'specialty': 'Cardiology',
    'availability': 'Evening',
    'schedule': 'Weekends',
    'area': 'Assima',
  },
  {
    'name': 'Dr. Layla',
    'specialty': 'Orthopedics',
    'availability': 'Afternoon',
    'schedule': 'Weekdays',
    'area': 'Hawally',
  },
  {
    'name': 'Dr. Khaled',
    'specialty': 'Dermatology',
    'availability': 'Morning',
    'schedule': 'Weekends',
    'area': 'Jahra',
  },
  {
    'name': 'Dr. Salma',
    'specialty': 'Gastroenterology',
    'availability': 'Evening',
    'schedule': 'Weekdays',
    'area': 'Assima',
  },
  {
    'name': 'Dr. Kareem',
    'specialty': 'Ophthalmology',
    'availability': 'Afternoon',
    'schedule': 'Weekends',
    'area': 'Hawally',
  },
  {
    'name': 'Dr. Fatima',
    'specialty': 'Cardiology',
    'availability': 'Morning',
    'schedule': 'Weekdays',
    'area': 'Jahra',
  },
  {
    'name': 'Dr. Hisham',
    'specialty': 'Orthopedics',
    'availability': 'Evening',
    'schedule': 'Weekends',
    'area': 'Assima',
  },
  {
    'name': 'Dr. Leila',
    'specialty': 'Dermatology',
    'availability': 'Afternoon',
    'schedule': 'Weekdays',
    'area': 'Hawally',
  },
];
